### ISSUE TITLE
Where should centos-systemd-etcs go?

### ISSUE THREAD

**Issue by ghostsquad** [Supervisor/initscripts#31]
Where should the `centos-systemd-etcs` file be put on Centos7?

**Comment by mnaberez** [comment]
That script was added by @ET-CS in 30ff7a4d98fc8b768fac49229a8faac0afc37917 so hopefully he can help with your question, if not you might try the [supervisor-users](https://lists.supervisord.org/mailman/listinfo/supervisor-users) mailing list.

**Comment by mnaberez** [comment]
Hopefully this was answered, if not [this comment](https://github.com/Supervisor/initscripts/issues/34#issue-121040118) might provide a clue where to put it.  

I'm going to close this issue because as noted in the README, the Supervisor maintainers didn't write these scripts and can't provide support for them. We are just collecting them here as a resource to try and help users.

**Comment by ET-CS** [comment]
Sorry for the late response.
If it'll help anyone, this file should copied to here: 
`/etc/systemd/system/supervisord.service`

**Comment by booox** [comment]
To me it doesn't work, `/etc/systemd/system/supervisord.service`
But when I move the *supervisord.servie* to *multi-user.target.wants* , it worked:
    `/etc/systemd/system/multi-user.target.wants/supervisord.service`
I don't know why.
